WITH RECURSIVE TMP_TBL AS (
     SELECT 0 AS HOUR
     UNION
     SELECT HOUR+1  FROM  TMP_TBL WHERE HOUR<23 ) 
     
SELECT HOUR, COUNT(DATETIME)
FROM TMP_TBL
LEFT JOIN ANIMAL_OUTS
ON HOUR=DATE_FORMAT(DATETIME, '%H')
#ON HOUR=HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR;
