WITH RECURSIVE TMP_TBL AS (
     SELECT 0 AS HOUR
     UNION
     SELECT HOUR+1  FROM  TMP_TBL WHERE HOUR<23 ) 
SELECT HOUR, COUNT(ANIMAL_ID)
FROM TMP_TBL
LEFT JOIN ANIMAL_OUTS
ON HOUR=DATE_FORMAT(DATETIME, '%H')
GROUP BY HOUR
ORDER BY HOUR;